# Generated by Django 3.2.7 on 2022-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('certificate', models.IntegerField(blank=True, choices=[(0, 'Young'), (1, 'Kid'), (2, 'General'), (3, 'Adult')], null=True)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=150)),
                ('imdb', models.FloatField()),
                ('metascore', models.FloatField(blank=True, null=True)),
                ('overview', models.CharField(max_length=10000)),
                ('director', models.CharField(max_length=150)),
                ('actors', models.CharField(max_length=600)),
            ],
        ),
    ]
